image: docker:latest

services:
  - docker:dind

stages:
  - build-docker
  
variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build-docker:
  stage: build-docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f Dockerfile -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

  only:
    - master

